name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
        pip install --upgrade buildozer cython

    - name: Setup Android SDK and Force Accept
      run: |
        # 1. Download & Extract Cmdline-tools
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        
        # 2. Path ke sdkmanager
        export PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin
        
        # 3. Force Accept Licenses (Ini mematikan error "Accept? (y/N)")
        yes "y" | sdkmanager --sdk_root=$HOME/android-sdk --licenses
        
        # 4. Install komponen yang kurang (Build-tools 37 & Platform 37)
        sdkmanager --sdk_root=$HOME/android-sdk "build-tools;37.0.0" "platforms;android-37" "platform-tools"
        
        # 5. Set environment variable agar Buildozer melihat SDK ini
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
