name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
        pip install --upgrade buildozer cython

    - name: Setup Android SDK and Fix Path
      run: |
        # 1. Buat direktori lisensi
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "d56f5187473751e9e7b235483257858c14f526c8" >> $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8713" >> $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        
        # 2. Unduh cmdline-tools
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        
        # 3. MENGAKALI PATH: Membuat symlink agar buildozer menemukan sdkmanager di tempat yang dia mau
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
        ln -s $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
